'use strict'

const fs = require('node:fs/promises')
const os = require('node:os')
const path = require('node:path')
const assert = require('node:assert/strict')
const test = require('node:test')
const { LocalFiles } = require('../lib/local-files.cjs')

test('local file tokens are owner-scoped, revoked on refresh and never expose file contents', async t => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'serverlink-local-'))
  t.after(() => fs.rm(directory, { recursive: true, force: true }))
  await fs.mkdir(path.join(directory, 'folder'))
  await fs.writeFile(path.join(directory, 'sample.txt'), 'not-for-renderer')
  await fs.symlink(path.join(directory, 'sample.txt'), path.join(directory, 'link'))
  const manager = new LocalFiles(directory)
  const listing = await manager.list(1)
  const file = listing.entries.find(entry => entry.name === 'sample.txt')
  const folder = listing.entries.find(entry => entry.name === 'folder')
  const link = listing.entries.find(entry => entry.name === 'link')
  assert.equal(listing.entries[0].name, 'folder')
  assert.equal(JSON.stringify(listing).includes('not-for-renderer'), false)
  assert.deepEqual(manager.selectedPaths(1, [file.id]), [path.join(directory, 'sample.txt')])
  assert.throws(() => manager.selectedPaths(2, [file.id]), /失效/u)
  assert.throws(() => manager.selectedPaths(1, ['/etc/passwd']), /失效/u)
  assert.throws(() => manager.selectedPaths(1, [folder.id]), /失效/u)
  assert.throws(() => manager.selectedPaths(1, [link.id]), /失效/u)
  assert.throws(() => manager.selectedPaths(1, [file.id, file.id]), /不同/u)
  const child = await manager.list(1, folder.id)
  assert.equal(child.path, path.join(directory, 'folder'))
  assert.throws(() => manager.selectedPaths(1, [file.id]), /失效/u)
  const parent = await manager.list(1, child.parentId)
  assert.equal(parent.path, directory)
  manager.closeOwner(1)
  await assert.rejects(manager.list(1, parent.id), /失效/u)
})
